### ISSUE TITLE
Error: All query arguments must be defined

### ISSUE THREAD

**Issue by awsed** [EasyGraphQL/easygraphql-load-tester#27]
Maybe I'm missing something, I'm trying to test subscriptions the are linked to specific mutations. Here's the code:

```javascript
'use strict'

const EasyGraphQLLoadTester = require('easygraphql-load-tester')
const fs = require('fs')
const path = require('path')

const rtSchema = fs.readFileSync(path.join(__dirname, 'schema.graphql'), 'utf8')

const args = {
  updateReviews: {
    input: {
      id: '3'
    }
  },
  createMessage: {
    message: 'test'
  }
}

const easyGraphQLLoadTester = new EasyGraphQLLoadTester(rtSchema, args)

const testCases = easyGraphQLLoadTester.artillery({
  withMutations: true
})

module.exports = {
  testCases
}
```

And I'm getting this error:

```
> npm run easygraphql-load-tester

> loadtester@1.0.0 easygraphql-load-tester /Users/edlima/Code/loadtester
> artillery run artillery.yml

.   /Users/edlima/Code/loadtester/node_modules/easygraphql-load-tester/utils/util.js:70
    throw new Error('All query arguments must be defined')
    ^

Error: All query arguments must be defined
    at createQueryArguments (/Users/xxxxx/Code/loadtester/node_modules/easygraphql-load-tester/utils/util.js:70:11)
    at create (/Users/xxxxx/Code/loadtester/node_modules/easygraphql-load-tester/utils/index.js:13:25)
    at schema.(anonymous function).fields.forEach.query (/Users/xxxxx/Code/loadtester/node_modules/easygraphql-load-tester/lib/loadTesting.js:25:30)
    at Array.forEach (<anonymous>)
    at LoadTesting.createQuery (/Users/xxxxx/Code/loadtester/node_modules/easygraphql-load-tester/lib/loadTesting.js:24:31)
    at LoadTesting.artillery (/Users/xxxxx/Code/loadtester/node_modules/easygraphql-load-tester/lib/loadTesting.js:47:26)
    at Object.<anonymous> (/Users/xxxxx/Code/loadtester/index.js:22:41)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! loadtester@1.0.0 easygraphql-load-tester: `artillery run artillery.yml`
npm ERR! Exit status 1
```

Any ideas?

**Comment by estrada9166** [comment]
@awsed do you have on your schema any query that receives arguments and is missing on the definition of the args?

**Comment by awsed** [comment]
Thanks for getting back to me. Yes, I do have these queries:

```
type Mutation {
	createMessage(message: String!): Message
	createMovies(input: CreateMoviesInput!): Movies
	updateMovies(input: UpdateMoviesInput!): Movies
	deleteMovies(input: DeleteMoviesInput!): Movies
	createReviews(input: CreateReviewsInput!): Reviews
	updateReviews(input: UpdateReviewsInput!): Reviews
	deleteReviews(input: DeleteReviewsInput!): Reviews
}

type Query {
	getMovies(id: ID!): Movies
	listMoviess(filter: ModelMoviesFilterInput, limit: Int, nextToken: String): ModelMoviesConnection
	getReviews(id: ID!): Reviews
	listReviewss(filter: ModelReviewsFilterInput, limit: Int, nextToken: String): ModelReviewsConnection
}
```

However I just want to test the mutations so I didn't define any queries in the args. Do I need to define all of them?

**Comment by estrada9166** [comment]
@awsed  No, you don't have to set all the args, but you should add the option with the queries/mutation you want to test:

```js
const testCases = easyGraphQLLoadTester.artillery({
  selectedQueries: ['updateReviews', 'createMessage'],
  withMutations: true
})
```

By default, it'll do load testing to all the queries; that way you can specify which queries/mutations should run!

**Comment by awsed** [comment]
It works now, thanks a lot!
